title: 9elmo6
description: Ammar Elmoghazy, an Electronics Engineering graduate, currently a Masters student at Ontario Tech University. My aim here is to share things that I have worked on, working on, and will work on, hopefully it would help someone out there. My Research interests - IoT ğŸ’», AI ğŸ¤¯, Electronics Engineering âš¡ï¸ . Non-research interest - Health ğŸ¥, Philosophy ğŸ’­, Psychology ğŸ§ .
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker